### ISSUE TITLE
Input prompt not displayed (on simple MUDs?)

### ISSUE THREAD

**Issue by xvxx** [LiquidityC/Blightmud#160] opened 2020-10-28 18:41 UTC
It seems that on very simple MUDs, Blightmud only prints to the output buffer when it encounters a newline.

I don't know a lot about MUD protocols, so I wanted to ask if this was intentional? I haven't dug in too much yet but there is obviously a bunch of Telnet protocol and prompt handling code in Blightmud that I assume is for more advanced MUDs.

The practical impact of this for me is that I play a MUD with a login prompt as well as an input prompt, and Blightmud doesn't render either of them properly.

Say I'm in a room that has an entrance to a library. If I type `library` and enter the room, this is what Blightmud prints:

> \> library 
> HP:100% CP:100% >> -[ Filmbook Library ]- 
> This is one of the biggest rooms in the Guild... 

If I just `telnet` into the MUD, I get my HP/CP as a prompt:

> HP:100% CP:100% >> _

And when I enter the library, I see:

> HP:100% CP:100% >> library
> -[ Filmbook Library ]-
> This is one of the biggest rooms in the Guild...

I get the same kind of "prompt eating" behavior from Blightmud when I run a test instance of [LDMud](https://github.com/ldmud/ldmud) locally. Upon login to my test MUD with Blightmud, I see:

> To log in, enter the name of your game character at the prompt, or just
'guest'. If this is your first time, a new character will be created and you
will be asked a for your password and couple of other things.
>
> Enjoy!
> 
> Version: 2.04.05

But when I just `telnet` in, I'm prompted to login:

> To log in, enter the name of your game character at the prompt, or just
> 'guest'. If this is your first time, a new character will be created and you
> will be asked a for your password and couple of other things.
> 
> Enjoy!
> 
> Version: 2.04.05
> What is your name: _

Any guidance would be appreciated, thank you!

**Comment by Xandaros** [comment] 2020-10-28 18:46
What MUDs does this happen on? Ideally one we can just connect to instead of needing to set up our own server.

I suspect they don't properly send an EOR, but I'd like to test it myself.

**Comment by xvxx** [comment] 2020-10-28 19:00
Here are a few MUDs where I get this behavior:

- coffeemud.net 23
- armageddon.org 4050
- mud.draknor.com 4000
- dunemud.net 6789

**Comment by Xandaros** [comment] 2020-10-28 19:11
I can replicate this behaviour on coffeemud. The login prompt does not show in Blightmud, but it does get sent.

The server does not send an EOR, but it does send a GA, which, looking at the code, should do the same thing.

**Comment by Xandaros** [comment] 2020-10-28 19:15
Ah, one thing that might be of note is that the GA gets sent in its own packet. I haven't looked too closely at what's actually going on, but maybe that has something to do with it.

I'll leave it to LiquidityC to actually figure out :P

**Comment by LiquidityC** [comment] 2020-10-28 20:12
I've seen this behavior on occasion. If we get GA or EOR it's usually not a problem. The problem is mostly with muds that don't send any prompt indicator.

I'll take a look when I get some time over.

I have an idea that this could be a problem with muds that claim to send a GA but then don't do it consistently. This might need some debugging.

**Comment by Xandaros** [comment] 2020-10-28 20:28
It definitely sends a GA:
```
[00:00:11.576] (7fec88d8f640) DEBUG  Read 16 bytes from stream
[00:00:11.576] (7fec88d8f640) DEBUG  Bytes: [10, 13, 65, 99, 99, 111, 117, 110, 116, 32, 110, 97, 109, 101, 58, 32]
[00:00:11.812] (7fec88d8f640) DEBUG  Read 2 bytes from stream
[00:00:11.812] (7fec88d8f640) DEBUG  Bytes: [255, 249]
[00:00:11.812] (7fec88d8f640) DEBUG  IAC: 249
[00:00:11.812] (7fec88d8f640) DEBUG  Setting telnet mode: TerminatedPrompt
```
The bytes sent are essentially:
```
"\n\rAccount name: "
IAC GA
```
It seems to recognize the prompt, but it doesn't print it.

**Comment by Xandaros** [comment] 2020-10-28 20:37
At least in the case of coffeemud, it seems it is only the first prompt that gets eaten. Looking at the code (net/telnet.rs:56):
```rust
                    match iac.command {
                        cmd::GA | cmd::EOR => {
                            let mut buffer = self.output_buffer.lock().unwrap();
                            if self.mode != TelnetMode::TerminatedPrompt {
                                debug!("Setting telnet mode: TerminatedPrompt");
                                self.mode = TelnetMode::TerminatedPrompt;
                                buffer.flush();
                            } else {
                                buffer.buffer_to_prompt(true);
                                self.main_writer.send(Event::Prompt).unwrap();
                            }
                        }
                        _ => {}
                    }
```
On the first GA or EOR it receives, it flushes the buffer and does nothing with the content. On subsequent ones, it will print it out.
Changing it to this:
```rust
                    match iac.command {
                        cmd::GA | cmd::EOR => {
                            let mut buffer = self.output_buffer.lock().unwrap();
                            if self.mode != TelnetMode::TerminatedPrompt {
                                debug!("Setting telnet mode: TerminatedPrompt");
                                self.mode = TelnetMode::TerminatedPrompt;
                                buffer.buffer_to_prompt(true);
                                self.main_writer.send(Event::Prompt).unwrap();
                                buffer.flush();
                            } else {
                                buffer.buffer_to_prompt(true);
                                self.main_writer.send(Event::Prompt).unwrap();
                            }
                        }
                        _ => {}
                    }
```
does fix it for coffeemud, but I wonder why it was implemented like this in the first place. Would this print garbage on some other MUDs?

**Comment by LiquidityC** [comment] 2020-10-28 21:51
That fix is probably valid. Likely just a miss that went unnoticed. I'm more concerned with the prompt being eaten on muds that don't send a terminating byte. Those are a lot harder to fix. Especially the ones that have a lot of descriptive text and stuff. 

Good spot though. If you feel like it you can PR and I'll merge it.

**Comment by LiquidityC** [comment] 2020-10-28 23:58
If anyone wants to dig more here since I won't be able to for a few days. `telnet.rs:handle_prompt()` is probably a good place to start debugging.

**Comment by LiquidityC** [comment] 2020-10-29 12:32
I know what the problem is here. I think Blightmud is "guessing" that the mud is a "NoPrompt" (MOO for example) mud in the early stages of connection. Later on when there actually is a prompt. This assumption is wrong but it prevents the mud from printing the prompt.

Simplest fix would be to remove the "NoPrompt" mode. It has little effect as is.

My goal was always to have the client make correct assumptions on the mud type on connection and never have the user worry about this stuff. But perhaps it's time to introduce options to force the prompt mode if it can't be correctly guessed.

**Comment by LiquidityC** [comment] 2020-10-29 12:50
We would also need to extend the "automatic prompt mode" selection with some information to the user about the choices made so that he/she will be able to change this if it's wrong.

**Comment by xvxx** [comment] 2020-10-29 15:17
Is there any way to have Blightmud start in NoPrompt but “be on the lookout” and suggest a mode change if it finds what looks like one? For most of the MUDs I shared above I think you hit the login prompt right away, so it’s not too long after connection. 

Happy to dig into this but it might take me a bit as I am new to the telnet protocol.

**Comment by LiquidityC** [comment] 2020-10-29 16:01
That could be an option. Essentially it works like this. Some muds send GA (go ahead) or EOR (end of read?) when they are done sending data. Clients can look for this byte and deduce when a prompt line has been received (the last line).

When a mud doesn't do this you can never be sure when you have received a prompt line. You can guess that it's the last line received in the tcp packet payload but in cases where mudoutput is large this will be sent in more then one packet. This can create a visual artifact where the client adds a newline when it prints what it thought was a prompt mid transmission. Essentially we added the NoPrompt mode to avoid this artifact on MOOs. Besides that it has very little effect.

**Comment by LiquidityC** [comment] 2020-10-30 14:20
I've been putting some thought into this. Initially I think we will drop the "NoPrompt" mode. Not getting a prompt is way worse then getting the occasional rogue newline. After that we can aim for a more robust solution. Not sure how we'd do that though but it'll be a future problem.

**Comment by LiquidityC** [comment] 2020-10-30 21:07
Closing this for now.

**Closed by LiquidityC** 2020-10-30 21:07 UTC
Labels: bug

**Comment by xvxx** [comment] 2020-10-30 22:29
Glorious. I'm now seeing the prompt in the output buffer at the right time. Thank you!
