### ISSUE TITLE
Support for MacOS keybindings

### ISSUE THREAD

**Issue by macjabeth** [LiquidityC/Blightmud#105] opened 2020-09-06 20:56 UTC
Hi! I've noticed that the keybindings given are Windows specific.

<img width="513" alt="CleanShot 2020-09-06 at 16 47 19@2x" src="https://user-images.githubusercontent.com/8473052/92334987-aa206d80-f060-11ea-9a6b-a909650669bf.png">

It'd be great to have those update/change for Mac users. For instance:

- `PgUp` -> `Fn + UpArrow`
- `PgDn` -> `Fn + DownArrow`
- `End` -> `Fn + RightArrow`
- etc.

Thank you!

**Comment by LiquidityC** [comment] 2020-09-07 04:41
Well not windows specific since Blightmud doesn't run on windows to my knowledge. Either way you can reconfigure the key bindings to your liking. Check out `/help bindings`. 

Also, my laptop doesn't have dedicated PgUP/PgDN keys and use the same combo you described with `Fb + Up arrow` this still send a pgup/pgdn event. I find it odd that Mac wouldn't have the same code for those keys since generally keyboards are more or less universal. 

Any other Mac users able to shine some light here?

**Comment by LiquidityC** [comment] 2020-09-07 06:10
A follow up question. Does the combo you described work for other applications in your terminal? I doubt this is something mac or implementation related after looking into some specs and documentation. `PgUp`, `PgDn`, `Home` and `End` aren't different on Linux, Mac Win. Eg. a keyboard is a keyboard and they send the same signals for the most part. Also, we have no control over the `Fn` key. That is hardware specific, caught and interpreted by the hardware before sending the key event signal.

**Comment by macjabeth** [comment] 2020-09-21 02:18
Hey @LiquidityC - I hadn't thought about specific keyboard implementations. I guess if I was using a separate wireless keyboard that was built differently, I could the specific characters to press. But for the built-in mac keyboard, it doesn't have them. It's a combination of pressing multiple keys together (see [docs](https://support.apple.com/en-us/HT201236)).

To answer your question though, yes those keyboard shortcuts work with other applications.

**Comment by LiquidityC** [comment] 2020-09-21 07:47
Ok, thanks. Since I don't own a macbook I'm going to need help debugging and solving this. The key event parser can be modified slightly to output when it doesn't recognize a command by printing the bytes. That should allow someone to debug this and see what keys a macbook is actually sending. Once that is figured out this should hopefully be a cakewalk.

This is what you'll want to modify, in particular the default match: [parse_key_event()](https://github.com/LiquidityC/Blightmud/blob/31cb053223d86684423bc3999bc9a2b48b2b9a78/src/ui/command.rs#L234-L262)

**Comment by LiquidityC** [comment] 2020-09-21 07:50
Ok, since I don't own a MacBook I'll need some help looking at this

The method [parse_key_event()](https://github.com/LiquidityC/Blightmud/blob/31cb053223d86684423bc3999bc9a2b48b2b9a78/src/ui/command.rs#L234-L262) can be modified in the default match case to print what bytes are actually being sent from the computer. This should let you get good information on the problem. Hopefully the solution should be a cakewalk after this point.

**Comment by xvxx** [comment] 2020-10-31 00:10
There are official Apple keyboards with `Page Up` and `Page Down` buttons, I use one with my iMac:

https://www.apple.com/shop/product/MQ052LL/A/magic-keyboard-with-numeric-keypad-us-english-silver

I am not sure there is any change warranted here, because if you try to google something like "page up button on macbook" it will point you to the keyboard shortcuts of `Fn` + `Up`, etc, which (as @LiquidityC points out) are not unique to Mac.

**Comment by LiquidityC** [comment] 2020-11-01 18:53
I confirmed that `Fn + PgUp/PgDn` works one a colleagues laptop so I don't think this is a 'global' issue. Closing.

**Closed by LiquidityC** 2020-11-01 18:53 UTC
Labels: good first issue, hacktoberfest, help wanted, investigation, osx
